source "https://rubygems.org"

gem "rake"

group :development, :test do
  gem "cucumber"
  gem "rspec"

  unless ENV["CI"]
    gem "guard-rspec"
    gem "pry"
    gem "rb-fsevent"
    gem 'terminal-notifier-guard'
  end
end
