AllCops:
  TargetRubyVersion: 2.5
  NewCops: disable
  Exclude:
    # exclude everything except lib dir
    - !ruby/regexp /^(?!lib\/)/

Bundler:
  Enabled: false

Gemspec:
  Enabled: false

Layout:
  Enabled: false

Lint:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Security:
  Enabled: true

Style:
  Enabled: false
