AllCops:
  TargetRubyVersion: 2.5
  NewCops: disable
  Exclude:
    # exclude all files except lib dir
    <% Dir.glob('**/*').grep_v(/^lib\//).each do |path| %>
    - <%= path %>
    <% end %>

Bundler:
  Enabled: false

Gemspec:
  Enabled: false

Layout:
  Enabled: false

Lint:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Security:
  Enabled: true

Style:
  Enabled: false
