---
name: BSON for Ruby
description: a fully featured [BSON specification](https://bsonspec.org/) implementation
  in Ruby
package: bson
jira: https://jira.mongodb.org/projects/RUBY
version:
  number: 5.2.0
  file: lib/bson/version.rb
